name: go-otm testvet

on: [push, pull_request]

jobs:
  testvet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Vet
        run: make vet
      - name: Test
        run: make test


